### PR TITLE
Minor fix to support cross platform compatibility to windows. 

### PR DESCRIPTION
**Pull request by ILightThings**
Small fix to support the file path format on windows. Should fix uploading and the title of the page.

### CODE REVIEW

**Comment by ILightThings** [comment]
Also, I apologize about the readme updates. I was nothing thinking when I made those changes and reverted them.

**Comment by patrickhener** [comment]
So it looks like you also reverted the change here. But I get the concept. Filepath instead of path. I will make the change myself and fix the other open issue later the day. Then I will publish a new Version

**Comment by patrickhener** [comment]
I fixed it with commit 23631a8. I am going to release a new version when fixing the other open issue.

**Comment by ILightThings** [comment]
Sorry about that. I am a bit new at contriuting and still learning best practices with github. Thanks for looking into this.

**Pull request closed without merging**
