### PR TITLE
Support installation via windows scoop package manager

### PR DESCRIPTION
**Pull request by IIpho3nix**
added the ability to install via the scoop package manager for windows (https://scoop.sh/)

### CODE REVIEW

**Comment by patrickhener** [comment]
So I understand this will enable users to use scoop to install goshs, right? This would also mean that I would need to take care of the scoop.json everytime I release a new version, right? I would need to change at least the version and the binary hashes. I don't think I wanna do that. There are several methods you can get goshs. All of them are rather "based" and do not include 3rd party tools like scoop (or nuget or apt or or). Someone hosted a binary version package in the arch user repositories (https://aur.archlinux.org/packages/goshs-bin) which is fine for me. But they take care of it. So I would suggest that you host a scoop.json somewhere, so people can pull it from there. If you want me to, I can add that to the README.md and goshs.de as an installation method.

**Comment by patrickhener** [comment]
Well I knew that I have seen that user handle once before. So yeah, that being said, what you say will be the best to do. Let's wait for the approval and I will keep the pull request open. Once the installer file is submitted and approved just let me know here and I can add it to the README.md then. And thanks for the interest in my project.

**Comment by IIpho3nix** [comment]
@patrickhener changes merged into scoop extras repository, can be installed by adding the extras bucket using `scoop bucket add extras` and then running the command `scoop install extras/goshs`

**Comment by patrickhener** [comment]
Commit 05a916f4813e04668cc0f8240f7b8cb119c5607a adds the description how to use it with scoop in the README.md and also on https://goshs.de. Thanks again for contributing.

**Pull request closed without merging**
